### ISSUE TITLE
Xbox Game Pass compatibility

### ISSUE THREAD

**Issue by jekasama** [WistfulHopes/UE4SSMods#1]
I assume this doesn't work with Xbox PC Pass version? Did the install correctly (at least I think so) and only the UI shows up, not the data needed.
![ngmi](https://github.com/WistfulHopes/UE4SSMods/assets/15354221/223207f0-98a6-4a87-9b2e-1d20a6626958)

**Comment by WistfulHopes** [comment]
Sadly it probably isn't feasible, since the Game Pass version isn't the same executable. I don't know if I can support both Steam and Game Pass easily.
